// @generated by scripts/gen-inference-pb.mjs from docs/reference/available-models-descriptor.txt
// 该文件是 Cursor 3.18.9 protobuf descriptor 的机械转写，请勿手改。
// 重新生成：node scripts/gen-inference-pb.mjs   校验：node scripts/gen-inference-pb.mjs --check
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/** @generated from enum aiserver.v1.AvailableModelsResponse.ConfirmationDialogue.Presentation */
export enum AvailableModelsResponse_ConfirmationDialogue_Presentation {
  /** @generated from enum value: PRESENTATION_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: PRESENTATION_POST_PICKER_WARNING = 1; */
  POST_PICKER_WARNING = 1,
}
proto3.util.setEnumType(AvailableModelsResponse_ConfirmationDialogue_Presentation, "aiserver.v1.AvailableModelsResponse.ConfirmationDialogue.Presentation", [
  { no: 0, name: "PRESENTATION_UNSPECIFIED" },
  { no: 1, name: "PRESENTATION_POST_PICKER_WARNING" },
]);

/** @generated from enum aiserver.v1.AvailableModelsResponse.DegradationStatus */
export enum AvailableModelsResponse_DegradationStatus {
  /** @generated from enum value: DEGRADATION_STATUS_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: DEGRADATION_STATUS_DEGRADED = 1; */
  DEGRADED = 1,
  /** @generated from enum value: DEGRADATION_STATUS_DISABLED = 2; */
  DISABLED = 2,
}
proto3.util.setEnumType(AvailableModelsResponse_DegradationStatus, "aiserver.v1.AvailableModelsResponse.DegradationStatus", [
  { no: 0, name: "DEGRADATION_STATUS_UNSPECIFIED" },
  { no: 1, name: "DEGRADATION_STATUS_DEGRADED" },
  { no: 2, name: "DEGRADATION_STATUS_DISABLED" },
]);

/** @generated from enum aiserver.v1.AvailableModelsResponse.ModelPickerBadge.Variant */
export enum AvailableModelsResponse_ModelPickerBadge_Variant {
  /** @generated from enum value: VARIANT_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: VARIANT_ACCENT = 1; */
  ACCENT = 1,
  /** @generated from enum value: VARIANT_NEUTRAL = 2; */
  NEUTRAL = 2,
  /** @generated from enum value: VARIANT_SUCCESS = 3; */
  SUCCESS = 3,
  /** @generated from enum value: VARIANT_WARN = 4; */
  WARN = 4,
  /** @generated from enum value: VARIANT_DANGER = 5; */
  DANGER = 5,
}
proto3.util.setEnumType(AvailableModelsResponse_ModelPickerBadge_Variant, "aiserver.v1.AvailableModelsResponse.ModelPickerBadge.Variant", [
  { no: 0, name: "VARIANT_UNSPECIFIED" },
  { no: 1, name: "VARIANT_ACCENT" },
  { no: 2, name: "VARIANT_NEUTRAL" },
  { no: 3, name: "VARIANT_SUCCESS" },
  { no: 4, name: "VARIANT_WARN" },
  { no: 5, name: "VARIANT_DANGER" },
]);

/** @generated from enum aiserver.v1.AvailableModelsResponse.ModelVendorId */
export enum AvailableModelsResponse_ModelVendorId {
  /** @generated from enum value: MODEL_VENDOR_ID_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: MODEL_VENDOR_ID_ANTHROPIC = 1; */
  ANTHROPIC = 1,
  /** @generated from enum value: MODEL_VENDOR_ID_OPENAI = 2; */
  OPENAI = 2,
  /** @generated from enum value: MODEL_VENDOR_ID_GOOGLE = 3; */
  GOOGLE = 3,
  /** @generated from enum value: MODEL_VENDOR_ID_XAI = 4; */
  XAI = 4,
  /** @generated from enum value: MODEL_VENDOR_ID_MOONSHOT = 5; */
  MOONSHOT = 5,
  /** @generated from enum value: MODEL_VENDOR_ID_CURSOR = 6; */
  CURSOR = 6,
  /** @generated from enum value: MODEL_VENDOR_ID_NVIDIA = 7; */
  NVIDIA = 7,
  /** @generated from enum value: MODEL_VENDOR_ID_ZAI = 8; */
  ZAI = 8,
  /** @generated from enum value: MODEL_VENDOR_ID_META = 9; */
  META = 9,
}
proto3.util.setEnumType(AvailableModelsResponse_ModelVendorId, "aiserver.v1.AvailableModelsResponse.ModelVendorId", [
  { no: 0, name: "MODEL_VENDOR_ID_UNSPECIFIED" },
  { no: 1, name: "MODEL_VENDOR_ID_ANTHROPIC" },
  { no: 2, name: "MODEL_VENDOR_ID_OPENAI" },
  { no: 3, name: "MODEL_VENDOR_ID_GOOGLE" },
  { no: 4, name: "MODEL_VENDOR_ID_XAI" },
  { no: 5, name: "MODEL_VENDOR_ID_MOONSHOT" },
  { no: 6, name: "MODEL_VENDOR_ID_CURSOR" },
  { no: 7, name: "MODEL_VENDOR_ID_NVIDIA" },
  { no: 8, name: "MODEL_VENDOR_ID_ZAI" },
  { no: 9, name: "MODEL_VENDOR_ID_META" },
]);

/** @generated from enum aiserver.v1.AvailableModelsScope */
export enum AvailableModelsScope {
  /** @generated from enum value: AVAILABLE_MODELS_SCOPE_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: AVAILABLE_MODELS_SCOPE_USER_AVAILABLE = 1; */
  USER_AVAILABLE = 1,
  /** @generated from enum value: AVAILABLE_MODELS_SCOPE_AUTOMATIONS = 2; */
  AUTOMATIONS = 2,
  /** @generated from enum value: AVAILABLE_MODELS_SCOPE_ADMIN_SETTINGS_ALL_APPLICATION_MODELS = 3; */
  ADMIN_SETTINGS_ALL_APPLICATION_MODELS = 3,
}
proto3.util.setEnumType(AvailableModelsScope, "aiserver.v1.AvailableModelsScope", [
  { no: 0, name: "AVAILABLE_MODELS_SCOPE_UNSPECIFIED" },
  { no: 1, name: "AVAILABLE_MODELS_SCOPE_USER_AVAILABLE" },
  { no: 2, name: "AVAILABLE_MODELS_SCOPE_AUTOMATIONS" },
  { no: 3, name: "AVAILABLE_MODELS_SCOPE_ADMIN_SETTINGS_ALL_APPLICATION_MODELS" },
]);

/** @generated from enum aiserver.v1.CloudAgentEffortMode */
export enum CloudAgentEffortMode {
  /** @generated from enum value: CLOUD_AGENT_EFFORT_MODE_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: CLOUD_AGENT_EFFORT_MODE_STANDARD = 1; */
  STANDARD = 1,
  /** @generated from enum value: CLOUD_AGENT_EFFORT_MODE_GRIND = 2; */
  GRIND = 2,
}
proto3.util.setEnumType(CloudAgentEffortMode, "aiserver.v1.CloudAgentEffortMode", [
  { no: 0, name: "CLOUD_AGENT_EFFORT_MODE_UNSPECIFIED" },
  { no: 1, name: "CLOUD_AGENT_EFFORT_MODE_STANDARD" },
  { no: 2, name: "CLOUD_AGENT_EFFORT_MODE_GRIND" },
]);

/** @generated from message agent.v1.RequestedModel.ModelParameterValue */
export class RequestedModel_ModelParameterValue extends Message<RequestedModel_ModelParameterValue> {
  /** @generated from field: string id = 1; */
  id: string = "";

  /** @generated from field: string value = 2; */
  value: string = "";

  constructor(data?: PartialMessage<RequestedModel_ModelParameterValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestedModel.ModelParameterValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestedModel_ModelParameterValue {
    return new RequestedModel_ModelParameterValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestedModel_ModelParameterValue {
    return new RequestedModel_ModelParameterValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestedModel_ModelParameterValue {
    return new RequestedModel_ModelParameterValue().fromJsonString(jsonString, options);
  }

  static equals(a: RequestedModel_ModelParameterValue | PlainMessage<RequestedModel_ModelParameterValue> | undefined, b: RequestedModel_ModelParameterValue | PlainMessage<RequestedModel_ModelParameterValue> | undefined): boolean {
    return proto3.util.equals(RequestedModel_ModelParameterValue, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsRequest */
export class AvailableModelsRequest extends Message<AvailableModelsRequest> {
  /** @generated from field: bool is_nightly = 1; */
  isNightly: boolean = false;

  /** @generated from field: bool include_long_context_models = 2; */
  includeLongContextModels: boolean = false;

  /** @generated from field: bool exclude_max_named_models = 3; */
  excludeMaxNamedModels: boolean = false;

  /** @generated from field: repeated string additional_model_names = 4; */
  additionalModelNames: string[] = [];

  /** @generated from field: optional bool use_model_parameters = 5; */
  useModelParameters?: boolean;

  /** @generated from field: optional bool include_hidden_models = 6; */
  includeHiddenModels?: boolean;

  /** @generated from field: optional bool do_not_use_markdown = 7; */
  doNotUseMarkdown?: boolean;

  /** @generated from field: optional bool variants_will_be_shown_in_exploded_list = 8; */
  variantsWillBeShownInExplodedList?: boolean;

  /** @generated from field: optional bool for_automations = 9; */
  forAutomations?: boolean;

  /** @generated from field: optional aiserver.v1.AvailableModelsScope scope = 10; */
  scope?: AvailableModelsScope;

  /** @generated from field: optional bool byok_enabled = 14; */
  byokEnabled?: boolean;

  /** @generated from field: optional bool use_react_model_picker = 11; */
  useReactModelPicker?: boolean;

  /** @generated from field: optional bool use_cloud_agent_effort_modes = 12; */
  useCloudAgentEffortModes?: boolean;

  /** @generated from field: optional string admin_settings_group_public_id = 13; */
  adminSettingsGroupPublicId?: string;

  constructor(data?: PartialMessage<AvailableModelsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_nightly", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "include_long_context_models", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "exclude_max_named_models", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "additional_model_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "use_model_parameters", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "include_hidden_models", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "do_not_use_markdown", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 8, name: "variants_will_be_shown_in_exploded_list", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 9, name: "for_automations", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 10, name: "scope", kind: "enum", T: proto3.getEnumType(AvailableModelsScope), opt: true },
    { no: 14, name: "byok_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 11, name: "use_react_model_picker", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 12, name: "use_cloud_agent_effort_modes", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 13, name: "admin_settings_group_public_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsRequest {
    return new AvailableModelsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsRequest {
    return new AvailableModelsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsRequest {
    return new AvailableModelsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsRequest | PlainMessage<AvailableModelsRequest> | undefined, b: AvailableModelsRequest | PlainMessage<AvailableModelsRequest> | undefined): boolean {
    return proto3.util.equals(AvailableModelsRequest, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse */
export class AvailableModelsResponse extends Message<AvailableModelsResponse> {
  /** @generated from field: repeated aiserver.v1.AvailableModelsResponse.AvailableModel models = 2; */
  models: AvailableModelsResponse_AvailableModel[] = [];

  /** @generated from field: repeated string model_names = 1; */
  modelNames: string[] = [];

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig composer_model_config = 4; */
  composerModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig cmd_k_model_config = 5; */
  cmdKModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig background_composer_model_config = 6; */
  backgroundComposerModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig plan_execution_model_config = 7; */
  planExecutionModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig spec_model_config = 8; */
  specModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig deep_search_model_config = 9; */
  deepSearchModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.FeatureModelConfig quick_agent_model_config = 10; */
  quickAgentModelConfig?: AvailableModelsResponse_FeatureModelConfig;

  /** @generated from field: map<string, AvailableModelsResponse_FeatureModelConfig> subagent_model_configs = 16; */
  subagentModelConfigs: { [key: string]: AvailableModelsResponse_FeatureModelConfig } = {};

  /** @generated from field: bool use_model_parameters = 11; */
  useModelParameters: boolean = false;

  /** @generated from field: optional int32 disable_unused_models_after_n_hours = 12; */
  disableUnusedModelsAfterNHours?: number;

  /** @generated from field: optional int32 upgrade_unchanged_models_after_n_hours = 13; */
  upgradeUnchangedModelsAfterNHours?: number;

  /** @generated from field: aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration display_configuration = 15; */
  displayConfiguration?: AvailableModelsResponse_ModelPickerDisplayConfiguration;

  /** @generated from field: optional string experimental_model_id = 19; */
  experimentalModelId?: string;

  /** @generated from field: optional string experimental_model_display_name = 20; */
  experimentalModelDisplayName?: string;

  /** @generated from field: optional string nudge_new_chats_to_auto_optimize_for = 21; */
  nudgeNewChatsToAutoOptimizeFor?: string;

  constructor(data?: PartialMessage<AvailableModelsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "models", kind: "message", T: AvailableModelsResponse_AvailableModel, repeated: true },
    { no: 1, name: "model_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "composer_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 5, name: "cmd_k_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 6, name: "background_composer_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 7, name: "plan_execution_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 8, name: "spec_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 9, name: "deep_search_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 10, name: "quick_agent_model_config", kind: "message", T: AvailableModelsResponse_FeatureModelConfig, opt: true },
    { no: 16, name: "subagent_model_configs", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: AvailableModelsResponse_FeatureModelConfig } },
    { no: 11, name: "use_model_parameters", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "disable_unused_models_after_n_hours", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 13, name: "upgrade_unchanged_models_after_n_hours", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 15, name: "display_configuration", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration },
    { no: 19, name: "experimental_model_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 20, name: "experimental_model_display_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 21, name: "nudge_new_chats_to_auto_optimize_for", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse {
    return new AvailableModelsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse {
    return new AvailableModelsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse {
    return new AvailableModelsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse | PlainMessage<AvailableModelsResponse> | undefined, b: AvailableModelsResponse | PlainMessage<AvailableModelsResponse> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.AvailableModel */
export class AvailableModelsResponse_AvailableModel extends Message<AvailableModelsResponse_AvailableModel> {
  /** @generated from field: string name = 1; */
  name: string = "";

  /** @generated from field: bool default_on = 2; */
  defaultOn: boolean = false;

  /** @generated from field: optional bool is_long_context_only = 3; */
  isLongContextOnly?: boolean;

  /** @generated from field: optional bool is_chat_only = 4; */
  isChatOnly?: boolean;

  /** @generated from field: optional bool supports_agent = 5; */
  supportsAgent?: boolean;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.DegradationStatus degradation_status = 6; */
  degradationStatus?: AvailableModelsResponse_DegradationStatus;

  /** @generated from field: optional double price = 7; */
  price?: number;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.TooltipData tooltip_data = 8; */
  tooltipData?: AvailableModelsResponse_TooltipData;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.TooltipData tooltip_data_for_max_mode = 20; */
  tooltipDataForMaxMode?: AvailableModelsResponse_TooltipData;

  /** @generated from field: optional bool supports_thinking = 9; */
  supportsThinking?: boolean;

  /** @generated from field: optional bool supports_images = 10; */
  supportsImages?: boolean;

  /** @generated from field: optional bool supports_auto_context = 11; */
  supportsAutoContext?: boolean;

  /** @generated from field: optional int32 auto_context_max_tokens = 12; */
  autoContextMaxTokens?: number;

  /** @generated from field: optional int32 auto_context_extended_max_tokens = 13; */
  autoContextExtendedMaxTokens?: number;

  /** @generated from field: optional bool supports_max_mode = 14; */
  supportsMaxMode?: boolean;

  /** @generated from field: optional bool supports_non_max_mode = 19; */
  supportsNonMaxMode?: boolean;

  /** @generated from field: optional int32 context_token_limit = 15; */
  contextTokenLimit?: number;

  /** @generated from field: optional int32 context_token_limit_for_max_mode = 16; */
  contextTokenLimitForMaxMode?: number;

  /** @generated from field: optional string client_display_name = 17; */
  clientDisplayName?: string;

  /** @generated from field: optional string server_model_name = 18; */
  serverModelName?: string;

  /** @generated from field: optional bool is_recommended_for_background_composer = 21; */
  isRecommendedForBackgroundComposer?: boolean;

  /** @generated from field: optional bool supports_plan_mode = 22; */
  supportsPlanMode?: boolean;

  /** @generated from field: optional bool supports_sandboxing = 25; */
  supportsSandboxing?: boolean;

  /** @generated from field: optional bool is_user_added = 23; */
  isUserAdded?: boolean;

  /** @generated from field: optional string inputbox_short_model_name = 24; */
  inputboxShortModelName?: string;

  /** @generated from field: optional bool supports_cmd_k = 26; */
  supportsCmdK?: boolean;

  /** @generated from field: optional bool only_supports_cmd_k = 27; */
  onlySupportsCmdK?: boolean;

  /** @generated from field: optional int32 background_composer_sort_order = 28; */
  backgroundComposerSortOrder?: number;

  /** @generated from field: repeated aiserver.v1.ModelParameterDefinition parameter_definitions = 29; */
  parameterDefinitions: ModelParameterDefinition[] = [];

  /** @generated from field: repeated aiserver.v1.AvailableModelsResponse.ModelVariantConfig variants = 30; */
  variants: AvailableModelsResponse_ModelVariantConfig[] = [];

  /** @generated from field: optional aiserver.v1.CloudAgentEffortMode cloud_agent_effort_mode = 32; */
  cloudAgentEffortMode?: CloudAgentEffortMode;

  /** @generated from field: optional string cloud_migrate_to_model = 33; */
  cloudMigrateToModel?: string;

  /** @generated from field: optional string upgrade_model_id = 34; */
  upgradeModelId?: string;

  /** @generated from field: optional bool is_hidden = 35; */
  isHidden?: boolean;

  /** @generated from field: repeated string legacy_slugs = 36; */
  legacySlugs: string[] = [];

  /** @generated from field: repeated string id_aliases = 37; */
  idAliases: string[] = [];

  /** @generated from field: optional int32 named_model_section_index = 38; */
  namedModelSectionIndex?: number;

  /** @generated from field: optional string tagline = 39; */
  tagline?: string;

  /** @generated from field: optional bool visible_in_routed_model_view = 40; */
  visibleInRoutedModelView?: boolean;

  /** @generated from field: optional string vendor_name = 41; */
  vendorName?: string;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelVendor vendor = 42; */
  vendor?: AvailableModelsResponse_ModelVendor;

  /** @generated from field: optional bool default_disabled_in_admin_allowlist = 43; */
  defaultDisabledInAdminAllowlist?: boolean;

  /** @generated from field: repeated aiserver.v1.CloudAgentEffortMode cloud_agent_effort_modes = 44; */
  cloudAgentEffortModes: CloudAgentEffortMode[] = [];

  /** @generated from field: optional bool supports_smart_mode_classifier = 45; */
  supportsSmartModeClassifier?: boolean;

  /** @generated from field: optional bool requires_data_retention = 46; */
  requiresDataRetention?: boolean;

  /** @generated from field: optional string reason_for_zdr_consent_block = 47; */
  reasonForZdrConsentBlock?: string;

  /** @generated from field: repeated aiserver.v1.AvailableModelsResponse.ModelPickerBadge model_picker_badges = 48; */
  modelPickerBadges: AvailableModelsResponse_ModelPickerBadge[] = [];

  constructor(data?: PartialMessage<AvailableModelsResponse_AvailableModel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.AvailableModel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "default_on", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "is_long_context_only", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "is_chat_only", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "supports_agent", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "degradation_status", kind: "enum", T: proto3.getEnumType(AvailableModelsResponse_DegradationStatus), opt: true },
    { no: 7, name: "price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 8, name: "tooltip_data", kind: "message", T: AvailableModelsResponse_TooltipData, opt: true },
    { no: 20, name: "tooltip_data_for_max_mode", kind: "message", T: AvailableModelsResponse_TooltipData, opt: true },
    { no: 9, name: "supports_thinking", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 10, name: "supports_images", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 11, name: "supports_auto_context", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 12, name: "auto_context_max_tokens", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 13, name: "auto_context_extended_max_tokens", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 14, name: "supports_max_mode", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 19, name: "supports_non_max_mode", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 15, name: "context_token_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 16, name: "context_token_limit_for_max_mode", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 17, name: "client_display_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 18, name: "server_model_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 21, name: "is_recommended_for_background_composer", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 22, name: "supports_plan_mode", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 25, name: "supports_sandboxing", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 23, name: "is_user_added", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 24, name: "inputbox_short_model_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 26, name: "supports_cmd_k", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 27, name: "only_supports_cmd_k", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 28, name: "background_composer_sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 29, name: "parameter_definitions", kind: "message", T: ModelParameterDefinition, repeated: true },
    { no: 30, name: "variants", kind: "message", T: AvailableModelsResponse_ModelVariantConfig, repeated: true },
    { no: 32, name: "cloud_agent_effort_mode", kind: "enum", T: proto3.getEnumType(CloudAgentEffortMode), opt: true },
    { no: 33, name: "cloud_migrate_to_model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 34, name: "upgrade_model_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 35, name: "is_hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 36, name: "legacy_slugs", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 37, name: "id_aliases", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 38, name: "named_model_section_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 39, name: "tagline", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 40, name: "visible_in_routed_model_view", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 41, name: "vendor_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 42, name: "vendor", kind: "message", T: AvailableModelsResponse_ModelVendor, opt: true },
    { no: 43, name: "default_disabled_in_admin_allowlist", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 44, name: "cloud_agent_effort_modes", kind: "enum", T: proto3.getEnumType(CloudAgentEffortMode), repeated: true },
    { no: 45, name: "supports_smart_mode_classifier", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 46, name: "requires_data_retention", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 47, name: "reason_for_zdr_consent_block", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 48, name: "model_picker_badges", kind: "message", T: AvailableModelsResponse_ModelPickerBadge, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_AvailableModel {
    return new AvailableModelsResponse_AvailableModel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_AvailableModel {
    return new AvailableModelsResponse_AvailableModel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_AvailableModel {
    return new AvailableModelsResponse_AvailableModel().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_AvailableModel | PlainMessage<AvailableModelsResponse_AvailableModel> | undefined, b: AvailableModelsResponse_AvailableModel | PlainMessage<AvailableModelsResponse_AvailableModel> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_AvailableModel, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ConfirmationDialogue */
export class AvailableModelsResponse_ConfirmationDialogue extends Message<AvailableModelsResponse_ConfirmationDialogue> {
  /** @generated from field: string title = 1; */
  title: string = "";

  /** @generated from field: string body = 2; */
  body: string = "";

  /** @generated from field: string key = 3; */
  key: string = "";

  /** @generated from field: bool blocks_submission = 4; */
  blocksSubmission: boolean = false;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ConfirmationDialogue.Presentation presentation = 5; */
  presentation?: AvailableModelsResponse_ConfirmationDialogue_Presentation;

  constructor(data?: PartialMessage<AvailableModelsResponse_ConfirmationDialogue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ConfirmationDialogue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "blocks_submission", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "presentation", kind: "enum", T: proto3.getEnumType(AvailableModelsResponse_ConfirmationDialogue_Presentation), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ConfirmationDialogue {
    return new AvailableModelsResponse_ConfirmationDialogue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ConfirmationDialogue {
    return new AvailableModelsResponse_ConfirmationDialogue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ConfirmationDialogue {
    return new AvailableModelsResponse_ConfirmationDialogue().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ConfirmationDialogue | PlainMessage<AvailableModelsResponse_ConfirmationDialogue> | undefined, b: AvailableModelsResponse_ConfirmationDialogue | PlainMessage<AvailableModelsResponse_ConfirmationDialogue> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ConfirmationDialogue, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.FeatureModelConfig */
export class AvailableModelsResponse_FeatureModelConfig extends Message<AvailableModelsResponse_FeatureModelConfig> {
  /** @generated from field: string default_model = 1; */
  defaultModel: string = "";

  /** @generated from field: repeated string fallback_models = 2; */
  fallbackModels: string[] = [];

  /** @generated from field: repeated string best_of_n_default_models = 3; */
  bestOfNDefaultModels: string[] = [];

  constructor(data?: PartialMessage<AvailableModelsResponse_FeatureModelConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.FeatureModelConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "default_model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fallback_models", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "best_of_n_default_models", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_FeatureModelConfig {
    return new AvailableModelsResponse_FeatureModelConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_FeatureModelConfig {
    return new AvailableModelsResponse_FeatureModelConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_FeatureModelConfig {
    return new AvailableModelsResponse_FeatureModelConfig().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_FeatureModelConfig | PlainMessage<AvailableModelsResponse_FeatureModelConfig> | undefined, b: AvailableModelsResponse_FeatureModelConfig | PlainMessage<AvailableModelsResponse_FeatureModelConfig> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_FeatureModelConfig, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerBadge */
export class AvailableModelsResponse_ModelPickerBadge extends Message<AvailableModelsResponse_ModelPickerBadge> {
  /** @generated from field: string label = 1; */
  label: string = "";

  /** @generated from field: aiserver.v1.AvailableModelsResponse.ModelPickerBadge.Variant variant = 2; */
  variant: AvailableModelsResponse_ModelPickerBadge_Variant = AvailableModelsResponse_ModelPickerBadge_Variant.UNSPECIFIED;

  /** @generated from field: bool dismiss_on_selection = 3; */
  dismissOnSelection: boolean = false;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerBadge>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerBadge";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "variant", kind: "enum", T: proto3.getEnumType(AvailableModelsResponse_ModelPickerBadge_Variant) },
    { no: 3, name: "dismiss_on_selection", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerBadge {
    return new AvailableModelsResponse_ModelPickerBadge().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerBadge {
    return new AvailableModelsResponse_ModelPickerBadge().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerBadge {
    return new AvailableModelsResponse_ModelPickerBadge().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerBadge | PlainMessage<AvailableModelsResponse_ModelPickerBadge> | undefined, b: AvailableModelsResponse_ModelPickerBadge | PlainMessage<AvailableModelsResponse_ModelPickerBadge> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerBadge, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration> {
  /** @generated from field: aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig routed_model_view_config = 1; */
  routedModelViewConfig?: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig;

  /** @generated from field: aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig named_models_view_config = 2; */
  namedModelsViewConfig?: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig;

  /** @generated from field: optional bool hide_search_bar = 3; */
  hideSearchBar?: boolean;

  /** @generated from field: optional bool hide_add_models = 4; */
  hideAddModels?: boolean;

  /** @generated from field: optional string model_selection_restriction_message = 5; */
  modelSelectionRestrictionMessage?: string;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "routed_model_view_config", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig },
    { no: 2, name: "named_models_view_config", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig },
    { no: 3, name: "hide_search_bar", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "hide_add_models", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "model_selection_restriction_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig> {
  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewToggle named_view_to_routed_model_view_toggle = 2; */
  namedViewToRoutedModelViewToggle?: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewNoButton named_view_to_routed_model_view_no_button = 3; */
  namedViewToRoutedModelViewNoButton?: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewButton named_view_to_routed_model_view_button = 4; */
  namedViewToRoutedModelViewButton?: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "named_view_to_routed_model_view_toggle", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle, opt: true },
    { no: 3, name: "named_view_to_routed_model_view_no_button", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton, opt: true },
    { no: 4, name: "named_view_to_routed_model_view_button", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewButton */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton> {
  /** @generated from field: string markdown = 1; */
  markdown: string = "";

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewButton";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "markdown", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewButton, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewNoButton */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton> {

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewNoButton";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewNoButton, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewToggle */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle> {
  /** @generated from field: string markdown = 1; */
  markdown: string = "";

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.NamedModelsViewConfig.NamedViewToRoutedModelViewToggle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "markdown", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_NamedModelsViewConfig_NamedViewToRoutedModelViewToggle, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig> {
  /** @generated from field: optional string title = 1; */
  title?: string;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewToggle routed_model_view_to_named_view_toggle = 2; */
  routedModelViewToNamedViewToggle?: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewButton routed_model_view_to_named_view_button = 3; */
  routedModelViewToNamedViewButton?: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton;

  /** @generated from field: optional bool hide_search_bar = 4; */
  hideSearchBar?: boolean;

  /** @generated from field: optional bool hide_routed_model_view = 5; */
  hideRoutedModelView?: boolean;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "routed_model_view_to_named_view_toggle", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle, opt: true },
    { no: 3, name: "routed_model_view_to_named_view_button", kind: "message", T: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton, opt: true },
    { no: 4, name: "hide_search_bar", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "hide_routed_model_view", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewButton */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton> {
  /** @generated from field: string markdown = 1; */
  markdown: string = "";

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewButton";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "markdown", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewButton, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewToggle */
export class AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle extends Message<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle> {
  /** @generated from field: string title_markdown = 1; */
  titleMarkdown: string = "";

  /** @generated from field: optional string subtitle = 2; */
  subtitle?: string;

  /** @generated from field: optional bool set_to_last_named_model = 3; */
  setToLastNamedModel?: boolean;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelPickerDisplayConfiguration.RoutedModelViewConfig.RoutedModelViewToNamedViewToggle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title_markdown", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subtitle", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "set_to_last_named_model", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle {
    return new AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle> | undefined, b: AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle | PlainMessage<AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelPickerDisplayConfiguration_RoutedModelViewConfig_RoutedModelViewToNamedViewToggle, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelVariantConfig */
export class AvailableModelsResponse_ModelVariantConfig extends Message<AvailableModelsResponse_ModelVariantConfig> {
  /** @generated from field: repeated agent.v1.RequestedModel.ModelParameterValue parameter_values = 1; */
  parameterValues: RequestedModel_ModelParameterValue[] = [];

  /** @generated from field: string display_name = 2; */
  displayName: string = "";

  /** @generated from field: optional string display_name_outside_picker = 8; */
  displayNameOutsidePicker?: string;

  /** @generated from field: bool is_max_mode = 3; */
  isMaxMode: boolean = false;

  /** @generated from field: optional bool is_default_max_config = 4; */
  isDefaultMaxConfig?: boolean;

  /** @generated from field: optional bool is_default_non_max_config = 5; */
  isDefaultNonMaxConfig?: boolean;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.TooltipData tooltip_data = 6; */
  tooltipData?: AvailableModelsResponse_TooltipData;

  /** @generated from field: optional string tagline = 7; */
  tagline?: string;

  /** @generated from field: optional string variant_string_representation = 9; */
  variantStringRepresentation?: string;

  /** @generated from field: optional aiserver.v1.AvailableModelsResponse.ConfirmationDialogue confirmation_dialogue = 10; */
  confirmationDialogue?: AvailableModelsResponse_ConfirmationDialogue;

  /** @generated from field: optional string legacy_slug = 11; */
  legacySlug?: string;

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelVariantConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelVariantConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "parameter_values", kind: "message", T: RequestedModel_ModelParameterValue, repeated: true },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "display_name_outside_picker", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "is_max_mode", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "is_default_max_config", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "is_default_non_max_config", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "tooltip_data", kind: "message", T: AvailableModelsResponse_TooltipData, opt: true },
    { no: 7, name: "tagline", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "variant_string_representation", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "confirmation_dialogue", kind: "message", T: AvailableModelsResponse_ConfirmationDialogue, opt: true },
    { no: 11, name: "legacy_slug", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelVariantConfig {
    return new AvailableModelsResponse_ModelVariantConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelVariantConfig {
    return new AvailableModelsResponse_ModelVariantConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelVariantConfig {
    return new AvailableModelsResponse_ModelVariantConfig().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelVariantConfig | PlainMessage<AvailableModelsResponse_ModelVariantConfig> | undefined, b: AvailableModelsResponse_ModelVariantConfig | PlainMessage<AvailableModelsResponse_ModelVariantConfig> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelVariantConfig, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.ModelVendor */
export class AvailableModelsResponse_ModelVendor extends Message<AvailableModelsResponse_ModelVendor> {
  /** @generated from field: aiserver.v1.AvailableModelsResponse.ModelVendorId id = 1; */
  id: AvailableModelsResponse_ModelVendorId = AvailableModelsResponse_ModelVendorId.UNSPECIFIED;

  /** @generated from field: string display_name = 2; */
  displayName: string = "";

  constructor(data?: PartialMessage<AvailableModelsResponse_ModelVendor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.ModelVendor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "enum", T: proto3.getEnumType(AvailableModelsResponse_ModelVendorId) },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_ModelVendor {
    return new AvailableModelsResponse_ModelVendor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelVendor {
    return new AvailableModelsResponse_ModelVendor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_ModelVendor {
    return new AvailableModelsResponse_ModelVendor().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_ModelVendor | PlainMessage<AvailableModelsResponse_ModelVendor> | undefined, b: AvailableModelsResponse_ModelVendor | PlainMessage<AvailableModelsResponse_ModelVendor> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_ModelVendor, a, b);
  }
}

/** @generated from message aiserver.v1.AvailableModelsResponse.TooltipData */
export class AvailableModelsResponse_TooltipData extends Message<AvailableModelsResponse_TooltipData> {
  /** @generated from field: string primary_text = 1; */
  primaryText: string = "";

  /** @generated from field: string secondary_text = 2; */
  secondaryText: string = "";

  /** @generated from field: bool secondary_warning_text = 3; */
  secondaryWarningText: boolean = false;

  /** @generated from field: string icon = 4; */
  icon: string = "";

  /** @generated from field: string tertiary_text = 5; */
  tertiaryText: string = "";

  /** @generated from field: string tertiary_text_url = 6; */
  tertiaryTextUrl: string = "";

  /** @generated from field: optional string markdown_content = 7; */
  markdownContent?: string;

  constructor(data?: PartialMessage<AvailableModelsResponse_TooltipData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.AvailableModelsResponse.TooltipData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "primary_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "secondary_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "secondary_warning_text", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tertiary_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "tertiary_text_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "markdown_content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AvailableModelsResponse_TooltipData {
    return new AvailableModelsResponse_TooltipData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AvailableModelsResponse_TooltipData {
    return new AvailableModelsResponse_TooltipData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AvailableModelsResponse_TooltipData {
    return new AvailableModelsResponse_TooltipData().fromJsonString(jsonString, options);
  }

  static equals(a: AvailableModelsResponse_TooltipData | PlainMessage<AvailableModelsResponse_TooltipData> | undefined, b: AvailableModelsResponse_TooltipData | PlainMessage<AvailableModelsResponse_TooltipData> | undefined): boolean {
    return proto3.util.equals(AvailableModelsResponse_TooltipData, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition */
export class ModelParameterDefinition extends Message<ModelParameterDefinition> {
  /** @generated from field: string id = 1; */
  id: string = "";

  /** @generated from field: string name = 2; */
  name: string = "";

  /** @generated from field: optional string markdown_tooltip = 3; */
  markdownTooltip?: string;

  /** @generated from field: aiserver.v1.ModelParameterDefinition.ModelParameterType parameter_type = 4; */
  parameterType?: ModelParameterDefinition_ModelParameterType;

  /** @generated from field: optional bool is_cycleable_by_hotkey = 5; */
  isCycleableByHotkey?: boolean;

  constructor(data?: PartialMessage<ModelParameterDefinition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "markdown_tooltip", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "parameter_type", kind: "message", T: ModelParameterDefinition_ModelParameterType },
    { no: 5, name: "is_cycleable_by_hotkey", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition {
    return new ModelParameterDefinition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition {
    return new ModelParameterDefinition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition {
    return new ModelParameterDefinition().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition | PlainMessage<ModelParameterDefinition> | undefined, b: ModelParameterDefinition | PlainMessage<ModelParameterDefinition> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition */
export class ModelParameterDefinition_BooleanParameterDefinition extends Message<ModelParameterDefinition_BooleanParameterDefinition> {
  /** @generated from field: repeated aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValue values = 1; */
  values: ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue[] = [];

  constructor(data?: PartialMessage<ModelParameterDefinition_BooleanParameterDefinition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "values", kind: "message", T: ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition_BooleanParameterDefinition {
    return new ModelParameterDefinition_BooleanParameterDefinition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition_BooleanParameterDefinition {
    return new ModelParameterDefinition_BooleanParameterDefinition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition_BooleanParameterDefinition {
    return new ModelParameterDefinition_BooleanParameterDefinition().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition_BooleanParameterDefinition | PlainMessage<ModelParameterDefinition_BooleanParameterDefinition> | undefined, b: ModelParameterDefinition_BooleanParameterDefinition | PlainMessage<ModelParameterDefinition_BooleanParameterDefinition> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition_BooleanParameterDefinition, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValue */
export class ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue extends Message<ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue> {
  /** @generated from field: string value = 1; */
  value: string = "";

  /** @generated from field: optional string display_name = 2; */
  displayName?: string;

  /** @generated from field: optional bool increases_model_cost = 3; */
  increasesModelCost?: boolean;

  /** @generated from field: optional bool default_blocked_in_admin_allowlist = 4; */
  defaultBlockedInAdminAllowlist?: boolean;

  /** @generated from field: optional bool hide_from_user_picker_when_admin_blocked = 5; */
  hideFromUserPickerWhenAdminBlocked?: boolean;

  /** @generated from field: optional bool blocked_by_admin_allowlist = 6; */
  blockedByAdminAllowlist?: boolean;

  constructor(data?: PartialMessage<ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "increases_model_cost", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "default_blocked_in_admin_allowlist", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "hide_from_user_picker_when_admin_blocked", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "blocked_by_admin_allowlist", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue {
    return new ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue {
    return new ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue {
    return new ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue | PlainMessage<ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue> | undefined, b: ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue | PlainMessage<ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition.EnumParameterDefinition */
export class ModelParameterDefinition_EnumParameterDefinition extends Message<ModelParameterDefinition_EnumParameterDefinition> {
  /** @generated from field: repeated aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValue values = 1; */
  values: ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue[] = [];

  constructor(data?: PartialMessage<ModelParameterDefinition_EnumParameterDefinition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition.EnumParameterDefinition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "values", kind: "message", T: ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition_EnumParameterDefinition {
    return new ModelParameterDefinition_EnumParameterDefinition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition_EnumParameterDefinition {
    return new ModelParameterDefinition_EnumParameterDefinition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition_EnumParameterDefinition {
    return new ModelParameterDefinition_EnumParameterDefinition().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition_EnumParameterDefinition | PlainMessage<ModelParameterDefinition_EnumParameterDefinition> | undefined, b: ModelParameterDefinition_EnumParameterDefinition | PlainMessage<ModelParameterDefinition_EnumParameterDefinition> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition_EnumParameterDefinition, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValue */
export class ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue extends Message<ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue> {
  /** @generated from field: string value = 1; */
  value: string = "";

  /** @generated from field: optional string display_name = 2; */
  displayName?: string;

  /** @generated from field: optional bool increases_model_cost = 3; */
  increasesModelCost?: boolean;

  /** @generated from field: optional bool blocked_by_admin_allowlist = 4; */
  blockedByAdminAllowlist?: boolean;

  /** @generated from field: optional string markdown_tooltip = 5; */
  markdownTooltip?: string;

  /** @generated from field: repeated aiserver.v1.AvailableModelsResponse.ModelPickerBadge model_picker_badges = 6; */
  modelPickerBadges: AvailableModelsResponse_ModelPickerBadge[] = [];

  constructor(data?: PartialMessage<ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "increases_model_cost", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "blocked_by_admin_allowlist", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "markdown_tooltip", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "model_picker_badges", kind: "message", T: AvailableModelsResponse_ModelPickerBadge, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue {
    return new ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue {
    return new ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue {
    return new ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue | PlainMessage<ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue> | undefined, b: ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue | PlainMessage<ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue, a, b);
  }
}

/** @generated from message aiserver.v1.ModelParameterDefinition.ModelParameterType */
export class ModelParameterDefinition_ModelParameterType extends Message<ModelParameterDefinition_ModelParameterType> {
  /** @generated from field: optional aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition boolean_parameter = 1; */
  booleanParameter?: ModelParameterDefinition_BooleanParameterDefinition;

  /** @generated from field: optional aiserver.v1.ModelParameterDefinition.EnumParameterDefinition enum_parameter = 2; */
  enumParameter?: ModelParameterDefinition_EnumParameterDefinition;

  constructor(data?: PartialMessage<ModelParameterDefinition_ModelParameterType>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.ModelParameterDefinition.ModelParameterType";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "boolean_parameter", kind: "message", T: ModelParameterDefinition_BooleanParameterDefinition, opt: true },
    { no: 2, name: "enum_parameter", kind: "message", T: ModelParameterDefinition_EnumParameterDefinition, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParameterDefinition_ModelParameterType {
    return new ModelParameterDefinition_ModelParameterType().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParameterDefinition_ModelParameterType {
    return new ModelParameterDefinition_ModelParameterType().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParameterDefinition_ModelParameterType {
    return new ModelParameterDefinition_ModelParameterType().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParameterDefinition_ModelParameterType | PlainMessage<ModelParameterDefinition_ModelParameterType> | undefined, b: ModelParameterDefinition_ModelParameterType | PlainMessage<ModelParameterDefinition_ModelParameterType> | undefined): boolean {
    return proto3.util.equals(ModelParameterDefinition_ModelParameterType, a, b);
  }
}
