// @generated by scripts/gen-inference-pb.mjs from docs/reference/grokbot-service-descriptor.txt
// 该文件是 Grok Bot 0.44.0 proto descriptor dump 的机械转写，请勿手改。
// 重新生成：node scripts/gen-inference-pb.mjs   校验：node scripts/gen-inference-pb.mjs --check
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/** @generated from enum aiserver.v1.SandBoxRunState */
export enum SandBoxRunState {
  /** @generated from enum value: SAND_BOX_RUN_STATE_UNSPECIFIED = 0; */
  UNSPECIFIED = 0,
  /** @generated from enum value: SAND_BOX_RUN_STATE_ABSENT = 1; */
  ABSENT = 1,
  /** @generated from enum value: SAND_BOX_RUN_STATE_HIBERNATED = 2; */
  HIBERNATED = 2,
  /** @generated from enum value: SAND_BOX_RUN_STATE_RUNNING = 3; */
  RUNNING = 3,
  /** @generated from enum value: SAND_BOX_RUN_STATE_STARTING = 4; */
  STARTING = 4,
}
proto3.util.setEnumType(SandBoxRunState, "aiserver.v1.SandBoxRunState", [
  { no: 0, name: "SAND_BOX_RUN_STATE_UNSPECIFIED" },
  { no: 1, name: "SAND_BOX_RUN_STATE_ABSENT" },
  { no: 2, name: "SAND_BOX_RUN_STATE_HIBERNATED" },
  { no: 3, name: "SAND_BOX_RUN_STATE_RUNNING" },
  { no: 4, name: "SAND_BOX_RUN_STATE_STARTING" },
]);

/** @generated from message aiserver.v1.EnsureSandBoxRequest */
export class EnsureSandBoxRequest extends Message<EnsureSandBoxRequest> {
  /** @generated from field: optional bool wake = 2; */
  wake?: boolean;

  constructor(data?: PartialMessage<EnsureSandBoxRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.EnsureSandBoxRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "wake", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnsureSandBoxRequest {
    return new EnsureSandBoxRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnsureSandBoxRequest {
    return new EnsureSandBoxRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnsureSandBoxRequest {
    return new EnsureSandBoxRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EnsureSandBoxRequest | PlainMessage<EnsureSandBoxRequest> | undefined, b: EnsureSandBoxRequest | PlainMessage<EnsureSandBoxRequest> | undefined): boolean {
    return proto3.util.equals(EnsureSandBoxRequest, a, b);
  }
}

/** @generated from message aiserver.v1.EnsureSandBoxResponse */
export class EnsureSandBoxResponse extends Message<EnsureSandBoxResponse> {
  /** @generated from field: string cluster = 1; */
  cluster: string = "";

  /** @generated from field: string tenant_id = 2; */
  tenantId: string = "";

  /** @generated from field: string pod_id = 3; */
  podId: string = "";

  /** @generated from field: string network_token = 4; */
  networkToken: string = "";

  /** @generated from field: string exec_daemon_auth_token = 5; */
  execDaemonAuthToken: string = "";

  /** @generated from field: string exec_daemon_url = 6; */
  execDaemonUrl: string = "";

  /** @generated from field: string vnc_url = 7; */
  vncUrl: string = "";

  /** @generated from field: string terminals_folder = 8; */
  terminalsFolder: string = "";

  /** @generated from field: string fork_vnc_base_url = 12; */
  forkVncBaseUrl: string = "";

  /** @generated from field: optional bool image_update_available = 9; */
  imageUpdateAvailable?: boolean;

  /** @generated from field: string gateway_url = 10; */
  gatewayUrl: string = "";

  /** @generated from field: string gateway_token = 11; */
  gatewayToken: string = "";

  /** @generated from field: aiserver.v1.SandBoxRunState run_state = 13; */
  runState: SandBoxRunState = SandBoxRunState.UNSPECIFIED;

  constructor(data?: PartialMessage<EnsureSandBoxResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "aiserver.v1.EnsureSandBoxResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cluster", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tenant_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pod_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "network_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "exec_daemon_auth_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "exec_daemon_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "vnc_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "terminals_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "fork_vnc_base_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "image_update_available", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 10, name: "gateway_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "gateway_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "run_state", kind: "enum", T: proto3.getEnumType(SandBoxRunState) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnsureSandBoxResponse {
    return new EnsureSandBoxResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnsureSandBoxResponse {
    return new EnsureSandBoxResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnsureSandBoxResponse {
    return new EnsureSandBoxResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EnsureSandBoxResponse | PlainMessage<EnsureSandBoxResponse> | undefined, b: EnsureSandBoxResponse | PlainMessage<EnsureSandBoxResponse> | undefined): boolean {
    return proto3.util.equals(EnsureSandBoxResponse, a, b);
  }
}
